const menu = [
    {
      id: 1,
      title: '3 Peynirli',
      category: 'tuzlu kruvasan',
      price: 60,
      img: './images/ucpeynir.jpeg',
      desc: `Kruvasan arasında çedar, çeçil suda mozarella ve scrambled egg, peynirli köz patlıcan, biber sos, grill zeytin, domates ve salatalık ile servis edilir. `,
    },
    {
      id: 2,
      title: "La'Lune Pesto",
      category: 'tuzlu kruvasan',
      price: 60,
      img: './images/pesto.jpg',
      desc: `Kruvasan arasında pesto sos, mozarella, scrambled egg, köz patlıcan, biber sos, grill zeytin, domates ve salatalık ile servis edilir. `,
    },
    {
      id: 3,
      title: 'Avokadolu Egg Boat',
      category: 'tuzlu kruvasan',
      price: 60,
      img: './images/avokadolueggboat.jpg',
      desc: `Scrambled egg ve avokado dip sos, zaytin, domates ve salatalık ile servis edilir.`
    },
    {
      id: 4,
      title: "La'Lune Frankfurter",
      category: 'tuzlu kruvasan',
      price: 70,
      img: './images/frankfurter.jpg',
      desc: `Kruvasan arasında dana frankfurter sosis, scrambled egg, cheddar peyniri, turşu sos yanında grill zeytin, avokado dip sos, domates ve salatalık ile servis edilir. `,
    },
    {
      id: 5,
      title: 'füme roast beef',
      category: 'tuzlu kruvasan',
      price: 60,
      img: './images/fumeroastbeef.jpg',
      desc: `Kruvasan arasında scrambled egg, füme et yanında grill zeytin, avokado dip sos, domates ve salatalık ile servis edilir. `,
    },
    {
      id: 6,
      title: "La'Lune Lotus",
      category: 'tatlı kruvasan',
      price: 55,
      img: './images/lotus.jpg',
      desc: `Kruvasan arasında Lotus kreması yanında muz, çilek ve file badem ile servis edilir.`,
    },
    {
      id: 7,
      title: "La'Lune Strawberry",
      category: 'tatlı kruvasan',
      price: 55,
      img: './images/strawberry.jpg',
      desc: `Kruvasan arasında pastacı kreması, çilek ve fıstık ile servis edilir. `,
    },
    {
      id: 8,
      title: "La'Lune Berry",
      category: 'tatlı kruvasan',
      price: 60,
      img: './images/berry.jpg',
      desc: `Kruvasan arasında orman meyveli pastacı kreması, file badem ve çikolata ile servis edilir.  `,
    },
    {
      id: 9,
      title: "La'Lune Lime",
      category: 'tatlı kruvasan',
      price: 55,
      img: './images/lime.jpg',
      desc: `Kruvasan arasında lime limonlu pastacı kreması, beyaz çikolata ile servis edilir.`,
    },
    {
        id: 10,
      title: "La'Lune Fıstık",
      category: 'tatlı kruvasan',
      price: 60,
      img: './images/fıstık.jpg',
      desc: `Kruvasan arasında fıstık kreması ve çikolata ile servis edilir.`,
    },
    {
        id: 11,
      title: "La'Lune Dark",
      category: 'tatlı kruvasan',
      price: 60,
      img: './images/dark.jpg',
      desc: `Dark kakaolu badem marzipan kavrulmuş badem ve bitter çikolata ile servis edilir.`,
    },
    {
        id: 12,
      title: "La'Lune Ruby",
      category: 'tatlı kruvasan',
      price: 60,
      img: './images/rubby.jpg',
      desc: `Krem patisserie frambuaz ve ruby çikolatanın efsanevi uyumu.`,
    },
   {
        id: 13,
      title: "Limonlu Cheesecake",
      category: 'Cheesecake',
      price: 38,
      img: 'https://cdn.yemek.com/mnresize/1250/833/uploads/2022/06/limonlu-cheesecake-serap.jpg',
      desc: ``
    },
      {
        id: 14,
      title: "Frambuazlı Cheesecake",
      category: 'Cheesecake',
      price: 38,
      img: 'https://www.happyhourorganizasyon.com/uploads/urun/b/frambuazli-cheesecake-dilim-160-g.png',
      desc: ``,
    },
     {
        id: 15,
      title: "Yabanmersinli Cheesecake",
      category: 'Cheesecake',
      price: 38,
      img: 'https://tarifist.com/back_end/images/tarifler/yaban_mersinli_cheesecake.webp',
      desc: ``,
    },
     {
        id: 16,
      title: "Lotuslu Cheesecake",
      category: 'Cheesecake',
      price: 38,
      img: 'https://res.cloudinary.com/dbrkydxfc/images/f_auto,q_auto:eco/w_2560,h_2560/v1627155970/lotus/lotus.jpg',
      desc: ``,
    },
     {
        id: 17,
      title: "Çikolatalı Cheesecake",
      category: 'Cheesecake',
      price: 38,
      img: 'https://renklihobi.com/wp-content/uploads/cikolatali-cheesecake-tarifi-.jpg',
      desc: ``,
    },
     {
        id: 18,
      title: "Makaron",
      category: 'Atıştırmalıklar',
      price: 10,
      img: 'https://iasbh.tmgrup.com.tr/d8fe22/800/420/0/129/1024/669?u=https://isbh.tmgrup.com.tr/sbh/2020/03/12/rengarenk-makaron-tarifi-makaron-nasil-yapilir-1584021891966.jpg',
      desc: ``,
    },
    {
        id: 19,
      title: "Dark Chocalate Cookie",
      category: 'Atıştırmalıklar',
      price: 20,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsMz3CrmP8YdigsCk3VdnOvH4iqEHmvMaoTMFg9MfFttRgSuQiV4UGVC_zRyuD1pKB4Pc&usqp=CAU',
      desc: ``,
    },
    {
        id: 20,
      title: "Üç Çikolatalı Cookie",
      category: 'Atıştırmalıklar',
      price: 20,
      img: 'https://i.elele.com.tr/2/1280/720/storage/files/images/2021/11/18/tripple-cookie-Mtgg_cover.jpg',
      desc: ``,
    },
    {
        id: 21,
      title: "Tuzlu Kurabiye",
      category: 'Atıştırmalıklar',
      price: 25,
      img: 'https://cdn.yemek.com/mncrop/940/625/uploads/2020/09/sirkeli-tuzlu-kurabiye-bayatlamayan-yemekcom.jpg',
      desc: ``,
    },
   
    {
        id: 23,
      title: "Sebastian",
      category: 'Sıcak Sunumlar',
      price: 40,
      img: 'https://limondilimi.com.tr/images/products/san-sebastian-cheesecake_000005',
      desc: `Belçika çikolatası ile servis edilir.`,
    },
       {
        id: 24,
      title: "Lune Green",
      category: 'Sıcak Sunumlar',
      price: 40,
      img: './images/LuneGreen.jpeg',
      desc: `Belçika çikolatası ile servis edilir.`,
    },
          {
        id: 25,
      title: "Paris Brest",
      category: 'Sıcak Sunumlar',
      price: 40,
      img: './images/Paris Brest.jpeg',
      desc: `Belçika çikolatası ile servis edilir.`,
    },
             {
        id: 26,
      title: "Lune Velvet",
      category: 'Sıcak Sunumlar',
      price: 40,
      img: './images/Lune Velvet.jpeg',
      desc: `Belçika çikolatası ile servis edilir.`,
    },
                {
        id: 27,
      title: "Lune Çikolata",
      category: 'Sıcak Sunumlar',
      price: 40,
      img: './images/Lune Çikolata.jpg',
      desc: `Belçika çikolatası ile servis edilir.`,
    },
                   {
        id: 28,
      title: "Brownie",
      category: 'Sıcak Sunumlar',
      price: 40,
      img: './images/Brownie.jpeg',
      desc: `Belçika çikolatası ile servis edilir.`,
    },
                      {
        id: 29,
      title: "Çilekli Tart",
      category: 'Sıcak Sunumlar',
      price: 40,
      img: './images/Çilek Tart.jpeg',
      desc: `Belçika çikolatası ile servis edilir.`,
    },
                        {
        id: 30,
      title: "Vişneli Muss Pasta",
      category: 'Pasta Çeşitleri',
      price: 40,
      img: '',
      desc: ``,
    },
                       {
        id: 31,
      title: "Çikolatalı Orman Meyveli Pasta",
      category: 'Pasta Çeşitleri',
      price: 40,
      img: '',
      desc: ``,
    },
                       {
        id: 32,
      title: "Double Çikolatalı Pasta",
      category: 'Pasta Çeşitleri',
      price: 40,
      img: '',
      desc: ``,
    },
                                              {
        id: 33,
      title: "Elmalı Tart",
      category: 'Pasta Çeşitleri',
      price: 35,
      img: '',
      desc: ``,
    },
                       {
        id: 34,
      title: "Dolce Peach",
      category: 'Pasta Çeşitleri',
      price: 40,
      img: '',
      desc: ``,
    },
                       {
        id: 35,
      title: "Budapeşte",
      category: 'Pasta Çeşitleri',
      price: 40,
      img: '',
      desc: ``,
    },
                          {
        id: 36,
      title: "Pavlova",
      category: 'Pasta Çeşitleri',
      price: 35,
      img: '',
      desc: ``,
    },    
                       {
        id: 37,
      title: "Espresso",
      category: 'Sıcak Kahveler',
      price: 15,
      img: '',
      desc: ``,
    },
                     {
        id: 38,
      title: "Americano",
      category: 'Sıcak Kahveler',
      price: 24,
      img: '',
      desc: ``,
    },
                     {
        id: 39,
      title: "Caffe Latte",
      category: 'Sıcak Kahveler',
      price: 24,
      img: '',
      desc: ``,
    },
                     {
        id: 40,
      title: "Flat White",
      category: 'Sıcak Kahveler',
      price: 28,
      img: '',
      desc: ``,
    },
                     {
        id: 41,
      title: "Double Espresso",
      category: 'Sıcak Kahveler',
      price: 21,
      img: '',
      desc: ``,
    },
                     {
        id: 42,
      title: "Cortado",
      category: 'Sıcak Kahveler',
      price: 28,
      img: '',
      desc: ``,
    },
                     {
        id: 43,
      title: "Filtre Kahve",
      category: 'Sıcak Kahveler',
      price: 28.75,
      img: '',
      desc: ``,
    },
                     {
        id: 44,
      title: "Sütlü Filtre Kahve",
      category: 'Sıcak Kahveler',
      price: 30,
      img: '',
      desc: ``,
    },
                     {
        id: 37,
      title: "Cappucino",
      category: 'Sıcak Kahveler',
      price: 27,
      img: '',
      desc: ``,
    },
                     {
        id: 45,
      title: "Sweet Latte",
      category: 'Özel Kahveler',
      price: 29,
      img: '',
      desc: `Böğürtlen , Fındık , Vanilya`,
    },
                                          {
        id: 46,
      title: "White Mocha",
      category: 'Özel Kahveler',
      price: 30.75,
      img: '',
      desc: ``,
    },
      {
        id: 47,
      title: "Irish Mocha",
      category: 'Özel Kahveler',
      price: 30.75,
      img: '',
      desc: ``,
    },
            {
        id: 48,
      title: "White Berry Mocha",
      category: 'Özel Kahveler',
      price: 30.75,
      img: '',
      desc: ``,
    },
      {
        id: 49,
      title: "Türk Kahvesi",
      category: 'Geleneksel Kahveler',
      price: 18,
      img: '',
      desc: ``,
    },
    {
        id: 50,
      title: "Menengiç Kahvesi",
      category: 'Geleneksel Kahveler',
      price: 20,
      img: '',
      desc: ``,
    },
    {
        id: 51,
      title: "Dibek Kahvesi",
      category: 'Geleneksel Kahveler',
      price: 20,
      img: '',
      desc: ``,
    },
    {
        id: 52,
      title: "Demleme Çay",
      category: 'Sıcak İçecekler',
      price: 8,
      img: '',
      desc: ``,
    },
    {
        id: 53,
      title: "Demleme Fincan Çay",
      category: 'Sıcak İçecekler',
      price: 8,
      img: '',
      desc: ``,
    },
    {
        id: 54,
      title: "Demleme Fincan Çay",
      category: 'Sıcak İçecekler',
      price: 14,
      img: '',
      desc: ``,
    },
    {
        id: 55,
      title: "Hot Chocalate",
      category: 'Sıcak İçecekler',
      price: 20,
      img: '',
      desc: ``,
    },
    {
        id: 56,
      title: "Chai Tea Latte",
      category: 'Sıcak İçecekler',
      price: 25,
      img: '',
      desc: ``,
    },
    {
        id: 57,
      title: "Sahlep",
      category: 'Sıcak İçecekler',
      price: 24,
      img: '',
      desc: ``,
    },
    {
        id: 58,
      title: "Çilekli Cooler ",
      category: 'Cooler',
      price: 28.75,
      img: '',
      desc: ``,
    },
    {
        id: 59,
      title: "Mango Cooler",
      category: 'Cooler',
      price: 28.75,
      img: '',
      desc: ``,
    },
    {
        id: 60,
      title: "Orman Meyveli Cooler",
      category: 'Cooler',
      price: 28.75,
      img: '',
      desc: ``,
    },
    {
        id: 60,
      title: "Kavun & Ananas Cooler",
      category: 'Cooler',
      price: 28.75,
      img: '',
      desc: ``,
    },
    {
        id: 61,
      title: "Çilekli Smoothie ",
      category: 'Smoothie',
      price: 30.75,
      img: '',
      desc: ``,
    },
    {
        id: 62,
      title: "Mango Smoothie ",
      category: 'Smoothie',
      price: 30.75,
      img: '',
      desc: ``,
    },
    {
        id: 63,
      title: "Orman Meyveli Smoothie ",
      category: 'Smoothie',
      price: 30.75,
      img: '',
      desc: ``,
    },
    {
        id: 64,
      title: "Kavun & Ananas Smoothie ",
      category: 'Smoothie',
      price: 30.75,
      img: '',
      desc: ``,
    },
    {
        id: 65,
      title: "Limonata ",
      category: 'Soğuk İçecekler',
      price: 22,
      img: '',
      desc: ``,
    },
    {
        id: 66,
      title: "Limonata Mint ",
      category: 'Soğuk İçecekler',
      price: 25,
      img: '',
      desc: ``,
    },
    {
        id: 67,
      title: "Limonata Berry ",
      category: 'Soğuk İçecekler',
      price: 25,
      img: '',
      desc: ``,
    },
    {
        id: 68,
      title: "Ice Lune ",
      category: 'Soğuk İçecekler',
      price: 28.25,
      img: '',
      desc: ``,
    },
    {
        id: 69,
      title: "Elderflavor ",
      category: 'Soğuk İçecekler',
      price: 26.75,
      img: '',
      desc: ``,
    },
    {
        id: 70,
      title: "Berry Hibiscus ",
      category: 'Soğuk İçecekler',
      price: 28.25,
      img: '',
      desc: ``,
    },
    {
        id: 70,
      title: "Cool Lime ",
      category: 'Soğuk İçecekler',
      price: 28.25,
      img: '',
      desc: ``,
    },
    {
        id: 71,
      title: "Mango Lime ",
      category: 'Soğuk İçecekler',
      price: 28.25,
      img: '',
      desc: ``,
    },
    {
        id: 72,
      title: "Ice Americano ",
      category: 'Soğuk Kahveler',
      price: 25.5,
      img: '',
      desc: ``,
    },
    {
        id: 73,
      title: "Ice Latte ",
      category: 'Soğuk Kahveler',
      price: 25.5,
      img: '',
      desc: ``,
    },
    {
        id: 74,
      title: "Ice Filtre Kahve ",
      category: 'Soğuk Kahveler',
      price: 30.25,
      img: '',
      desc: ``,
    },
    {
        id: 75,
      title: "Ice Sütlü Filtre Kahve",
      category: 'Soğuk Kahveler',
      price: 31.75,
      img: '',
      desc: ``,
    },
    {
        id: 76,
      title: "Ice Sweet Latte",
      category: 'Özel Kahveler',
      price: 30.50,
      img: '',
      desc: `Böğürtlen , Fındık , Vanilya`,
    },
                                          {
        id: 77,
      title: "Ice White Mocha",
      category: 'Özel Kahveler',
      price: 32.25,
      img: '',
      desc: ``,
    },
      {
        id: 78,
      title: "Ice Irish Mocha",
      category: 'Özel Kahveler',
      price: 32.25,
      img: '',
      desc: ``,
    },
            {
        id: 79,
      title: "Ice White Berry Mocha",
      category: 'Özel Kahveler',
      price: 32.25,
      img: '',
      desc: ``,
    },
    {
        id: 80,
      title: "Menekşe",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 81,
      title: "Çikolata",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 82,
      title: "Sade",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 83,
      title: "Çilek",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 84,
      title: "Şeftali",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 85,
      title: "Vişne",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 86,
      title: "Kavun",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 87,
      title: "Mango",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 88,
      title: "Snickers",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 89,
      title: "Yoğurt",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 90,
      title: "İtalyan Karameli",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 91,
      title: "Meksika Vanilyası",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 92,
      title: "Limon",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 93,
      title: "Lime",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 94,
      title: "Ceviz",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 95,
      title: "Fındık",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 96,
      title: "Yaban Mersini",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 97,
      title: "Böğürtlen",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
    {
        id: 98,
      title: "Hindistan Cevizi",
      category: 'Dondurma',
      price: 11,
      img: '',
      desc: ``,
    },
  ];

  export default menu;
  
  