const menu = [
  {
    id: 1,
    title: '3 Peynirli',
    category: 'tuzlu kruvasan',
    price: 60,
    img: './images/ucpeynir.jpeg',
    desc: `Kruvasan arasında çedar, çeçil suda mozarella ve scrambled egg, peynirli köz patlıcan, biber sos, grill zeytin, domates ve salatalık ile servis edilir. `,
  },
  {
    id: 2,
    title: "La'Lune Pesto",
    category: 'tuzlu kruvasan',
    price: 60,
    img: './images/pesto.jpg',
    desc: `Kruvasan arasında pesto sos, mozarella, scrambled egg, köz patlıcan, biber sos, grill zeytin, domates ve salatalık ile servis edilir. `,
  },
  {
    id: 3,
    title: 'Avokadolu Egg Boat',
    category: 'tuzlu kruvasan',
    price: 60,
    img: './images/avokadolueggboat.jpg',
    desc: `Scrambled egg ve avokado dip sos, zaytin, domates ve salatalık ile servis edilir.`
  },
  {
    id: 4,
    title: "La'Lune Frankfurter",
    category: 'tuzlu kruvasan',
    price: 70,
    img: './images/frankfurter.jpg',
    desc: `Kruvasan arasında dana frankfurter sosis, scrambled egg, cheddar peyniri, turşu sos yanında grill zeytin, avokado dip sos, domates ve salatalık ile servis edilir. `,
  },
  {
    id: 5,
    title: 'füme roast beef',
    category: 'tuzlu kruvasan',
    price: 60,
    img: './images/fumeroastbeef.jpg',
    desc: `Kruvasan arasında scrambled egg, füme et yanında grill zeytin, avokado dip sos, domates ve salatalık ile servis edilir. `,
  },
  {
    id: 6,
    title: "La'Lune Lotus",
    category: 'tatlı kruvasan',
    price: 55,
    img: './images/lotus.jpg',
    desc: `Kruvasan arasında Lotus kreması yanında muz, çilek ve file badem ile servis edilir.`,
  },
  {
    id: 7,
    title: "La'Lune Strawberry",
    category: 'tatlı kruvasan',
    price: 55,
    img: './images/strawberry.jpg',
    desc: `Kruvasan arasında pastacı kreması, çilek ve fıstık ile servis edilir. `,
  },
  {
    id: 8,
    title: "La'Lune Berry",
    category: 'tatlı kruvasan',
    price: 60,
    img: './images/berry.jpg',
    desc: `Kruvasan arasında orman meyveli pastacı kreması, file badem ve çikolata ile servis edilir.  `,
  },
  {
    id: 9,
    title: "La'Lune Lime",
    category: 'tatlı kruvasan',
    price: 55,
    img: './images/lime.jpg',
    desc: `Kruvasan arasında lime limonlu pastacı kreması, beyaz çikolata ile servis edilir.`,
  },
  {
      id: 10,
    title: "La'Lune Fıstık",
    category: 'tatlı kruvasan',
    price: 60,
    img: './images/fıstık.jpg',
    desc: `Kruvasan arasında fıstık kreması ve çikolata ile servis edilir.`,
  },
  {
      id: 11,
    title: "La'Lune Dark",
    category: 'tatlı kruvasan',
    price: 60,
    img: './images/dark.jpg',
    desc: `Dark kakaolu badem marzipan kavrulmuş badem ve bitter çikolata ile servis edilir.`,
  },
  {
      id: 12,
    title: "La'Lune Ruby",
    category: 'tatlı kruvasan',
    price: 60,
    img: './images/rubby.jpg',
    desc: `Krem patisserie frambuaz ve ruby çikolatanın efsanevi uyumu.`,
  },
];
export default menu;
